### ISSUE TITLE
Problem building and circular dependencies

### ISSUE THREAD

**Issue by noa** [gvvaughan/lyaml#11] opened 2015-09-16 19:46 UTC
Tried building lyaml from a rockspec, got this:

checking if Lua header version matches 5.1... no
configure: error: cannot find headers for specified LUA_INCLUDE

Couldn't find any settings of LUA_INCLUDE / LUA that worked, so I tried building from source, which gives:

bootstrap:   error: Prerequisite LuaRock 'specl 14' not found. Please install it.
bootstrap:   error: Missing rocks:

However:

$ luarocks install specl
Installing https://luarocks.org/specl-14.1.2-1.src.rock...
Using https://luarocks.org/specl-14.1.2-1.src.rock... switching to 'build' mode

Missing dependencies for specl:
lyaml >= 5

**Comment by gvvaughan** [comment] 2015-09-16 20:26
> On 16 Sep 2015, at 20:46, Nicholas Andrews <notifications@github.com> wrote:
> 
> Tried building lyaml from a rockspec, got this:
> 
> checking if Lua header version matches 5.1… no

Do you have the Lua 5.1 headers installed? (/usr/include/lua5.1/lua.h or similar)

> configure: error: cannot find headers for specified LUA_INCLUDE

I forget the details (though luarocks has documentation on its website), but if your Lua header files are installed in /usr/include/lua5.1 then you should build with LUA_INCLUDE=/usr/include/lua5.1.

> Couldn't find any settings of LUA_INCLUDE / LUA that worked, so I tried building from source, which gives:
> 
> bootstrap: error: Prerequisite LuaRock 'specl 14' not found. Please install it.
> bootstrap: error: Missing rocks:

Well, that’s bootstrapping from git, which is a level beyond building from source.  You do need specl to bootstrap, but you can build from one of the tarballs at https://github.com/gvvaughan/lyaml/releases without specl.  You will still need Lua header files and library, and libyaml headers and library though.

> However:
> 
> $ luarocks install specl
> Installing https://luarocks.org/specl-14.1.2-1.src.rock...
> Using https://luarocks.org/specl-14.1.2-1.src.rock... switching to 'build' mode
> 
> Missing dependencies for specl:
> lyaml >= 5

HTH,
Gary

**Comment by noa** [comment] 2015-09-16 21:00
Yes, and configure appears to be finding them, only failing on that last check. The path in LUA_INCLUDE below is correct: 

./configure LUA='lua' LUA_INCLUDE='-I/pkg/lua/5.1/include' ...

checking for specl... :
checking if lua is a Lua interpreter... yes
checking whether lua version >= 5.1, < 5.4... yes
checking for lua version... 5.1
checking for lua platform... unknown
checking for lua script directory... ${prefix}/share/lua/5.1
checking for lua module directory... ${exec_prefix}/lib/lua/5.1
checking if LUA_VERSION is defined... yes
checking lua.h usability... yes
checking lua.h presence... yes
checking for lua.h... yes
checking lualib.h usability... yes
checking lualib.h presence... yes
checking for lualib.h... yes
checking lauxlib.h usability... yes
checking lauxlib.h presence... yes
checking for lauxlib.h... yes
checking luaconf.h usability... yes
checking luaconf.h presence... yes
checking for luaconf.h... yes
checking for Lua header version... unknown
checking if Lua header version matches 5.1... no
configure: error: cannot find headers for specified LUA_INCLUDE

**Comment by noa** [comment] 2015-09-16 21:10
Possibly related to this issue:

https://github.com/luaposix/luaposix/issues/136

**Comment by gvvaughan** [comment] 2015-09-20 13:27
Hi Nicholas,

Sorry for the late reply.  I don't think this is #136 related, since that was about problems with calls to grep, which we're no longer using.  The error message you're experiencing (`Lua header version... unknown`) is only generated when this C program is unable to find LUA_VERSION definition in the lua headers you point it at:

```C
#include <lua.h>
#include <stdlib.h>
#include <stdio.h>
int main(int argc, char ** argv)
{
  if(argc > 1) printf("%s", LUA_VERSION);
  exit(EXIT_SUCCESS);
}
```

If you compile this by hand against the headers you pointed configure at, what happens?  If it doesn't work, then your headers are misinstalled/mismatched against your interpreter; otherwise if it does work', configure itself is getting confused by the paths you're passing in.

What does `config.log` show around the error message?  That might give you a clue as to where things came off the rails too.

HTH,
Gary

**Comment by GUI** [comment] 2015-10-07 02:41
I'm not entirely sure if it's the same underlying issue, but I hit the same `checking for Lua header version… unknown` error. Here's the `config.log` from that installation attempt: https://gist.github.com/GUI/df6ae5a95b20ccc2ea1f#file-config-log-L498-L548

In my case, I was trying to install lyaml against a manual build of libyaml in a custom location, which I think was causing the problems. I was specifying `YAML_DIR` to give the location of the custom libyaml installation, which allowed luarocks to pass the sanity checks for being able to locate the libyaml.so file. However, what seems to be happening is that then this `conftest` file gets compiled with the proper flags pointing to the custom libyaml location:

```
configure:13574: gcc -o conftest -g -O2 -I/tmp/api-umbrella-build/embedded/include -I/tmp/api-umbrella-build/embedded/openresty/luajit/include/luajit-2.1 -L/tmp/api-umbrella-build/embedded/lib conftest.c -lyaml  >&5
```

The compile succeeds, but then when it goes to actually run the test file, it blows up, since it can't locate libyaml.so at runtime (since there's no environment variables indicating the custom paths on the run command):

```
configure:13574: ./conftest
./conftest: error while loading shared libraries: libyaml-0.so.2: cannot open shared object file: No such file or directory
```

So at least in my case, the fact that configure is complaining about the Lua version is a bit of a red herring, since this test is actually bombing because of linking issues to the libyaml library.

I wasn't successful in getting lyaml to install via luarocks with libyaml in a custom location (I tired various environment variables to force the custom path to no avail). However, I was able to sidestep the issue by installing against libyaml installed in the default system directories (`/usr/lib`). But it seems like there might be an issue here if you are trying to use `YAML_DIR` or `YAML_LIBDIR` (which I think are the environment variables luarocks expects) to link against libyaml in a custom location.

**Comment by gvvaughan** [comment] 2015-10-07 21:22
Great information, thank you! And I think we can fix this by using Libtool to link the contest so that the rpaths are properly set. I'll set aside some time to experiment over the weekend if I don't get to it sooner, and close this issue if I'm successful.

Thanks again!

**Closed** 2015-10-11 17:27 UTC

**Comment by gvvaughan** [comment] 2015-10-11 17:32
No need for Libtool hoop jumping after all, I was able to wrap the -lyaml tests to stop them affecting the subsequent LUA_HEADERS test.  70eac0d definitely corrects the `checking for Lua header version... unknown` problem.

I'm pretty sure that a luarocks install should now pass along YAML_LIBDIR and YAML_INCDIR for non standard directories correctly too.  If not please raise a separate issue and I'll look into that some more.

**Comment by gvvaughan** [comment] 2015-10-11 17:34
btw, if anyone who did have this problem can confirm that the issue is fixed for them, I'll make a new point release to luarocks from current master.

**Comment by nelson2005** [comment] 2016-09-12 14:15
FWIW, I ran into what seems to be the same issue installing on a recent juajit

```
  inflating: lyaml-release-v6.0/specs/specs.mk
  inflating: lyaml-release-v6.0/travis.yml.in
./configure LUA='/home/nbk9tfs/openresty-1.11.2.1/luajit/bin/luajit-2.1.0-beta2' LUA_INCLUDE='-I/home/nbk9tfs/openresty-1.11.2.1/luajit/include/luajit-2.1' CPPFLAGS='-I/home/nbk9tfs/usr/local/include' LDFLAGS='-L/home/nbk9tfs/usr/local/lib' --prefix='/home/nbk9tfs/openresty-1.11.2.1/luajit/lib/luarocks/rocks/lyaml/6.0-1' --libdir='/home/nbk9tfs/openresty-1.11.2.1/luajit/lib/luarocks/rocks/lyaml/6.0-1/lib' --datadir='/home/nbk9tfs/openresty-1.11.2.1/luajit/lib/luarocks/rocks/lyaml/6.0-1/lua' --datarootdir='/home/nbk9tfs/openresty-1.11.2.1/luajit/lib/luarocks/rocks/lyaml/6.0-1' && make clean all
## --------------------- ##
## Configuring lyaml 6.0 ##
## --------------------- ##

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for ANSI C header files... (cached) yes
checking yaml.h usability... yes
checking yaml.h presence... yes
checking for yaml.h... yes
checking for library containing yaml_document_initialize... -lyaml
checking for specl... :
checking if /home/nbk9tfs/openresty-1.11.2.1/luajit/bin/luajit-2.1.0-beta2 is a Lua interpreter... yes
checking whether /home/nbk9tfs/openresty-1.11.2.1/luajit/bin/luajit-2.1.0-beta2 version >= 5.1, < 5.4... yes
checking for /home/nbk9tfs/openresty-1.11.2.1/luajit/bin/luajit-2.1.0-beta2 version... 5.1
checking for /home/nbk9tfs/openresty-1.11.2.1/luajit/bin/luajit-2.1.0-beta2 platform... unknown
checking for /home/nbk9tfs/openresty-1.11.2.1/luajit/bin/luajit-2.1.0-beta2 script directory... ${prefix}/share/lua/5.1
checking for /home/nbk9tfs/openresty-1.11.2.1/luajit/bin/luajit-2.1.0-beta2 module directory... ${exec_prefix}/lib/lua/5.1
checking if LUA_VERSION is defined... yes
checking lua.h usability... yes
checking lua.h presence... yes
checking for lua.h... yes
checking lualib.h usability... yes
checking lualib.h presence... yes
checking for lualib.h... yes
checking lauxlib.h usability... yes
checking lauxlib.h presence... yes
checking for lauxlib.h... yes
checking luaconf.h usability... yes
checking luaconf.h presence... yes
checking for luaconf.h... yes
checking for Lua header version... unknown
checking if Lua header version matches 5.1... no
configure: error: cannot find headers for specified LUA_INCLUDE

Error: Build error: Failed building.

```

**Comment by gvvaughan** [comment] 2016-09-17 05:26
can you post a link or a gist to the resulting config.log file for me to look through, please?

**Comment by achalddave** [comment] 2016-10-07 16:04
I had the same issue. Here's the relevant excerpt from the config.log file: https://gist.github.com/achalddave/1162e2c40f679b4eec1985d90688ecb6

**Comment by gvvaughan** [comment] 2016-10-07 17:01
Ah! I hadn't considered that people would want to link against a locally installed libyaml on GNU/Linux without adding that directory to `/etc/ld.so.conf` and running `ldconfig` to set the OS runtime linker paths up before using them. If you can install libyaml with your package manager, it will do that automatically; but if not, setting LD_LIBRARY_PATH as you describe is the right solution.

I'll add some notes to that effect to the README file. Thank you for the pointer!
