### ISSUE TITLE
Directory 'doc' not found error on luarocks installation

### ISSUE THREAD

**Issue by mjbryant** [gvvaughan/lyaml#16] opened 2017-01-23 17:15 UTC
I'm getting a "Directory 'doc' not found" error when trying to install 6.1.1. This is on a fresh, relatively simple docker image: https://gist.github.com/mjbryant/3bbb7b41eac91d450b2771b2d896c1e0

**Comment by gvvaughan** [comment] 2017-01-23 19:38
Thanks for the report.

The problem is that the install is expecting to have access to a working ldoc executable to build the contents of the documents directory on the fly. I should include prebuilt docs in the release.

In the mean time `luarocks install ldoc` will get you going.

**Comment by gvvaughan** [comment] 2017-01-24 15:50
Fixed by ab1fdef917cb71159d15219f0079caef55c12c7d

**Closed by gvvaughan** 2017-01-24 15:50 UTC
